version: '3'

services:
  portainer:
    image: diquzart/go-app:latest
    container_name: app1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=http"
      - "traefik.http.routers.app.rule=Host(`hello-app.iquzart.ga`)"
      ## Middlewares Rules
      - traefik.http.routers.app.middlewares=https-redirect@file
      ## Router rules secure
      - traefik.http.routers.app-https.rule=Host(`hello-app.iquzart.ga`)
      - traefik.http.routers.app-https.entrypoints=https
      - traefik.http.routers.app-https.tls=true
      - traefik.http.routers.app-https.tls.certresolver=letsencrypt
      ## Service Rules
      - "traefik.http.services.app-https.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
  app_net:
    external: false
