# Dynamic configuration
http:
  middlewares:
    user-auth:
      basicAuth:
        users:
          - "admin:$apr1$i7a3kbz8$LDQm4Hj1uSeRsNy1B1wBL0"

    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
        port: 443  

    demo-whitelist:
      ipWhiteList:
        sourceRange:
         - 127.0.0.1/32 
